services:
- name: tars
  namespace: mann
  environments:
  - gargantua
  generator:
    service:
      template: endr-robot
    gitops:
      template: helm-service
  overrides:
    gateway:
      enabled: true
    image: calavelas/endr-robot:c68ef1a
    env:
      ROBOT_NAME: TARS
      HUMOR: '90'
      HONESTY: '90'
      TRUST: '70'
      CATCHPHRASE: Plenty of slaves for my robot colony.
      ENDR_ALLOW_SELF_DESTRUCT: 'false'
- name: case
  namespace: edmunds
  environments:
  - gargantua
  generator:
    service:
      template: endr-robot
    gitops:
      template: helm-service
  overrides:
    gateway:
      enabled: true
    image: calavelas/endr-robot:c68ef1a
    env:
      ROBOT_NAME: CASE
      HUMOR: '30'
      HONESTY: '95'
      TRUST: '90'
      CATCHPHRASE: See you on the other side.
      ENDR_ALLOW_SELF_DESTRUCT: 'false'