replicaCount: 1
image:
  repository: calavelas/api
  tag: 38ea4d3
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
httpRoute:
  enabled: true
  name: api-route
  hostnames:
  - api.k8s.local
  pathPrefix: /
  parentRefs:
  - name: gateway-traefik
    namespace: gateway
    sectionName: http
  - name: gateway-traefik
    namespace: gateway
    sectionName: https
env:
  IDP_REPO_ROOT: /workspace
  API_ARGOCD_SERVER: http://argocd-server.argocd.svc.cluster.local
  API_ARGOCD_VERIFY_TLS: 'false'
  API_TXN_STATUS_OPEN_CACHE_MS: '60000'
  API_TXN_STATUS_CLOSED_CACHE_MS: '900000'
  API_HISTORY_REFRESH_MAX_CANDIDATES: '3'
  API_HISTORY_REFRESH_STALE_MS: '600000'
argocdTokenSecret:
  enabled: false
  name: api-argocd-token
  key: token
  optional: false
githubTokenSecret:
  enabled: true
  name: api-github-token
  key: GITHUB_TOKEN
  optional: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi
