apiVersion: v1
kind: Service
metadata:
  name: tryout-rover
spec:
  selector:
    app.kubernetes.io/name: tryout-rover
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
