apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aaa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/calavelas/ENDR.git
    targetRevision: main
    path: SVCS/aaa/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: miller1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
